export const allProjects = [
  {
    title: "Y Combinator Kanban System Simulation",
    description: "Built a Kanban-style task system for a logistics startup in a job simulation with Y Combinator on Forage.",
    tech: ["Node.js", "React", "SQL", "Product Thinking", "Simulation"],
    role: "Full-stack dev + analytics: drag-and-drop UI, backend persistence, product feature recommendations",
    website: "https://www.theforage.com/virtual-internships/prototype/BotenCEjm3LFxtq9A/Y-Combinator-Software-Engineering",
    demo: ""
  },
  {
    title: "Vista Equity Partners AI Workflow Simulation",
    description: "Designed GenAI prompt workflows to automate customer feedback summaries and news insights for Vista’s Portfolio Operations team.",
    tech: ["Prompt Engineering", "ChatGPT", "GenAI", "Simulation"],
    role: "Prompt design, feedback iteration, workflow automation, quality control",
    website: "https://www.theforage.com/completion-certificates/BotenCEjm3LFxtq9A/EregFenDKXDDeTGR2_BotenCEjm3LFxtq9A_696d6afb8d5b9c666d473801_1768788410360_completion_certificate.pdf",
    demo: ""
  },
    {
      title: "SoftSkills LMS System",
      description: "Dynamic course and quiz platform built with PHP, MySQL, and Bootstrap.",
      tech: ["PHP", "CodeIgniter", "MySQL", "JS", "HTML", "CSS"],
      role: "Full-stack development, admin UI, quiz logic, certificate gen",
      website: "https://mentor.unm.edu/softskills",
      demo: "",
    },
    {
      title: "Publication Download Tracker",
      description: "Lightweight PHP-based tracker that logs downloads of academic publications with IP address and timestamps, integrated into a research portal.",
      tech: ["PHP", "CodeIgniter", "MySQL", "HTML", "Bootstrap"],
      role: "Backend logic, model integration, download logging, and dashboard UI embedding",
      github: "https://github.com/dhakalsaurav11/tracker",
      website: "https://mentor.unm.edu/tracker/analytics",
      demo: "",
    },
    
    {
      title: "CS351 Fire Propagation Simulator",
      description: "Simulates wildfire spread using sensors and mobile agents with C++ and GTK GUI.",
      tech: ["Java", "Graph Theory", "File I/O", "School Project"],
      role: "Network logic, SensorNode, propagation, agent debugging",
      github: "https://github.com/UNM-CS351/multi-chef-lab-dhakalsaurav11",
      demo: "",
    },
    {
      title: "Shopify 'Bushido' Theme",
      description: "Custom-built theme with ethical branding, custom Liquid, and Samurai aesthetics.",
      tech: ["Shopify Liquid", "HTML", "Tailwind", "JS"],
      role: "Theme creation, styling, login page UX redesign",
      github: "https://github.com/dhakalsaurav11/bushido-theme",
      demo: "",
    },
    {
      title: "Stock Tracker & Trade Engine",
      description: "Built a stock tracker with technical analysis, triggers, and sentiment-based alerts.",
      tech: ["Python", "Flask", "Yahoo Finance API", "SQLite"],
      role: "Backend API, trade logic, watchlist UI",
      github: "https://github.com/dhakalsaurav11/stx-terminal",
      demo: "",
    },
    {
      title: "AERA Abstract Scraper",
      description: "Python script to scrape research abstracts across paginated search results.",
      tech: ["Python", "Requests", "BeautifulSoup", "CSV"],
      role: "Multi-page scraper, CSV writer, page handler",
      github: "https://github.com/dhakalsaurav11/aera-emails-scraper",
      demo: "",
    },
    {
      title: "Scrabble Game",
      description: "Playable GUI version of Scrabble with tile rules, board logic, and scoring system.",
      tech: ["Java", "Swing", "School Project"],
      role: "Board logic, GUI rendering, JAR packaging",
      github: "https://github.com/UNM-CS351/project-3-scrabble-dhakalsaurav11",
      demo: "",
    },
    {
      title: "Auctions Game",
      description: "A distributed auction system simulating real-time interactions between agents, auction houses, and a central bank using Java sockets and JavaFX.",
      tech: ["Java", "School Project"],
      role: "Board logic, GUI rendering, JAR packaging",
      github: "https://github.com/UNM-CS351/project-5-auctions-project-5-group-02-1",
      demo: "",
    },
  ];
