export const allProjects = [
    {
      title: "SoftSkills LMS System",
      description: "Dynamic course and quiz platform built with PHP, MySQL, and Bootstrap.",
      tech: ["PHP", "CodeIgniter", "MySQL", "JS", "HTML", "CSS"],
      role: "Full-stack development, admin UI, quiz logic, certificate gen",
      website: "https://mentor.unm.edu/softskills",
      demo: "",
      image: "/screenshots/softskills.png",
    },
    {
      title: "CS351 Fire Propagation Simulator",
      description: "Simulates wildfire spread using sensors and mobile agents with C++ and GTK GUI.",
      tech: ["Java", "Graph Theory", "File I/O"],
      role: "Network logic, SensorNode, propagation, agent debugging",
      github: "https://github.com/UNM-CS351/multi-chef-lab-dhakalsaurav11",
      demo: "",
      image: "/screenshots/fire-sim.png",
    },
    {
      title: "Shopify 'Bushido' Theme",
      description: "Custom-built theme with ethical branding, custom Liquid, and Samurai aesthetics.",
      tech: ["Shopify Liquid", "HTML", "Tailwind", "JS"],
      role: "Theme creation, styling, login page UX redesign",
      github: "https://github.com/dhakalsaurav11/bushido-theme",
      demo: "",
      image: "/screenshots/shopify-theme.png",
    },
    {
      title: "Stock Tracker & Trade Engine",
      description: "Built a stock tracker with technical analysis, triggers, and sentiment-based alerts.",
      tech: ["Python", "Flask", "Yahoo Finance API", "SQLite"],
      role: "Backend API, trade logic, watchlist UI",
      github: "https://github.com/dhakalsaurav11/stx-terminal",
      demo: "",
      image: "/screenshots/stock-tracker.png",
    },
    {
      title: "AERA Abstract Scraper",
      description: "Python script to scrape research abstracts across paginated search results.",
      tech: ["Python", "Requests", "BeautifulSoup", "CSV"],
      role: "Multi-page scraper, CSV writer, page handler",
      github: "https://github.com/dhakalsaurav11/aera-emails-scraper",
      demo: "",
      image: "/screenshots/aera-scraper.png",
    },
    {
      title: "Scrabble Game",
      description: "Playable GUI version of Scrabble with tile rules, board logic, and scoring system.",
      tech: ["Java", "Swing"],
      role: "Board logic, GUI rendering, JAR packaging",
      github: "https://github.com/UNM-CS351/project-3-scrabble-dhakalsaurav11",
      demo: "",
      image: "/screenshots/scrabble.png",
    },
    {
      title: "Auctions Game",
      description: "A distributed auction system simulating real-time interactions between agents, auction houses, and a central bank using Java sockets and JavaFX.",
      tech: ["Java"],
      role: "Board logic, GUI rendering, JAR packaging",
      github: "https://github.com/UNM-CS351/project-5-auctions-project-5-group-02-1",
      demo: "",
      image: "/screenshots/auctions.png",
    },
  ];
