export const allProjects = [
    {
      title: "SoftSkills LMS System",
      description: "Dynamic course and quiz platform built with PHP, MySQL, and Bootstrap.",
      tech: ["PHP", "CodeIgniter", "MySQL", "JS", "HTML", "CSS"],
      role: "Full-stack development, admin UI, quiz logic, certificate gen",
      github: "https://github.com/dhakalsaurav11/softskills",
      demo: "",
      image: "/screenshots/softskills.png",
    },
    {
      title: "CS351 Fire Propagation Simulator",
      description: "Simulates wildfire spread using sensors and mobile agents with C++ and GTK GUI.",
      tech: ["Java", "Graph Theory", "File I/O"],
      role: "Network logic, SensorNode, propagation, agent debugging",
      github: "https://github.com/dhakalsaurav11/cs351-fire-sim",
      demo: "",
      image: "/screenshots/fire-sim.png",
    },
    {
      title: "Shopify 'Bushido' Theme",
      description: "Custom-built theme with ethical branding, custom Liquid, and Samurai aesthetics.",
      tech: ["Shopify Liquid", "HTML", "Tailwind", "JS"],
      role: "Theme creation, styling, login page UX redesign",
      github: "https://github.com/dhakalsaurav11/bushido-theme",
      demo: "",
      image: "/screenshots/shopify-theme.png",
    },
    {
      title: "Bomb Lab (Reverse Engineering)",
      description: "Disassembled 6-phase binary using GDB to identify logic, recursion, and jump tables.",
      tech: ["C", "Assembly", "GDB"],
      role: "Reverse engineering, logic tracing, ASM debugging",
      github: "https://github.com/dhakalsaurav11/bomb-lab",
      demo: "",
      image: "/screenshots/bomb-lab.png",
    },
    {
      title: "Stock Tracker & Trade Engine",
      description: "Built a stock tracker with technical analysis, triggers, and sentiment-based alerts.",
      tech: ["Python", "Flask", "Yahoo Finance API", "SQLite"],
      role: "Backend API, trade logic, watchlist UI",
      github: "https://github.com/dhakalsaurav11/stock-tracker",
      demo: "",
      image: "/screenshots/stock-tracker.png",
    },
    {
      title: "AERA Abstract Scraper",
      description: "Python script to scrape research abstracts across paginated search results.",
      tech: ["Python", "Requests", "BeautifulSoup", "CSV"],
      role: "Multi-page scraper, CSV writer, page handler",
      github: "https://github.com/dhakalsaurav11/aera-scraper",
      demo: "",
      image: "/screenshots/aera-scraper.png",
    },
    {
      title: "Scrabble Game GUI",
      description: "Playable GUI version of Scrabble with tile rules, board logic, and scoring system.",
      tech: ["Java", "Swing"],
      role: "Board logic, GUI rendering, JAR packaging",
      github: "https://github.com/dhakalsaurav11/scrabble-game",
      demo: "",
      image: "/screenshots/scrabble.png",
    },
    {
      title: "Merge Sort Visualizer",
      description: "Step-by-step sorting visualizer for understanding recursive divide-and-conquer.",
      tech: ["C++", "Python (Alt Option)"],
      role: "Algorithm design, visual explanation tool",
      github: "https://github.com/dhakalsaurav11/merge-sort-visualizer",
      demo: "",
      image: "/screenshots/merge-sort.png",
    },
  ];
  